apiVersion: v1
kind: Service
metadata:
   
  name: my-todo-postgres
  labels:
    my-todo-app-service: my-todo-postgres
spec:
  type: ClusterIP
  selector:
    my-todo-app-pod: my-todo-postgres
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432