apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ template "mytodo.fullname" . }}-mytodo
  name: my-todo-elastic-data-pvc
spec:
  #storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi