apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "mytodo.fullname" . }}-mytodo
  name: my-todo-api
  labels:
    my-todo-app-service: my-todo-api
spec:
  type: ClusterIP
  selector:
    my-todo-app-pod: my-todo-api
  ports:
  - name: "http"
    port: 3000
    targetPort: 3000