apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "mytodo.fullname" . }}-mytodo
  name: my-todo-redis
  labels:
    my-todo-app-service: my-todo-redis
spec:
  type: ClusterIP
  selector:
    my-todo-app-pod: my-todo-redis
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
status:
  loadBalancer: {}