apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   
  name: my-todo-postgres-data-pvc
spec:
  #storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi