apiVersion: v1
kind: Service
metadata:
   
  name: my-todo-elastic
  labels:
    my-todo-app-service: my-todo-elastic
spec:
  type: ClusterIP
  selector:
    my-todo-app-pod: my-todo-elastic
  ports:
  - name: es-http
    port: 9200
    targetPort: 9200
  - name: es-transport
    port: 9300
    targetPort: 9300