apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "mytodo.fullname" . }}-mytodo
  name: my-todo-proxy
  labels:
    my-todo-app-service: my-todo-proxy

spec:
  #type: LoadBalancer
  type: ClusterIP
  selector:
    my-todo-app-pod: my-todo-proxy
  ports:
  - name: "8081"
    port: 8081
    targetPort: 80
