#apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
   
  name: my-todo-api
  labels:
    my-todo-app-deployment: my-todo-api
spec:
  replicas: {{ .Values.replicas.mytodoApi }}
  selector:
      matchLabels:
        my-todo-app-pod: my-todo-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        my-todo-app-pod: my-todo-api
    spec:
      restartPolicy: Always
      containers:
      - name: my-todo-api
        image: {{ .Values.todoImageUser }}/my-todo-api:{{ .Values.todoVersion }}
        #command: ['sh', '-c', '/app/start.sh']
        envFrom:
          - configMapRef:
              name: my-todo-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-todo-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "134217728"