apiVersion: v1
kind: Service
metadata:
   
  name: my-todo-view
  labels:
    my-todo-app-service: my-todo-view
spec:
  type: ClusterIP
  selector:
    my-todo-app-pod: my-todo-view
  ports:
  - name: "4200"
    port: 4200
    targetPort: 4200
